### ISSUE TITLE
Github Icon is not showing up in any Projects

### ISSUE THREAD

**Issue by aromalanil** [liyasthomas/website#30]
## **Describe the bug**
The Github icon is not showing up on any project page.

## **To Reproduce**
Steps to reproduce the behaviour:
1. Go to any project page
2. You will see the icon has not loaded

## **Screenshots**
![image](https://user-images.githubusercontent.com/49222186/92411029-da046980-f163-11ea-90b4-bed58e80e43c.png)

**Comment by liyasthomas** [comment]
![Capture](https://user-images.githubusercontent.com/10395817/92422159-c70c8c00-f199-11ea-8987-9dfb53fe3137.PNG)

works fine at my end. can you try force refreshing your browser. (Ctrl + Shift + R)

**Comment by aromalanil** [comment]
Ha Okay then, that might be my issue.
